CREATE DATABASE IF NOT EXISTS myproject;
USE myproject;

CREATE TABLE IF NOT EXISTS logincreds (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
);
