version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: sriram
      DB_PASSWORD: Sriram#2225
      DB_NAME: login_system

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: login_system
      MYSQL_USER: sriram
      MYSQL_PASSWORD: Sriram#2225
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
